### ISSUE TITLE
NanoVer examples/fundamentals/servers.ipynb uses "Narupa" not "NanoVer" in diagrams

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#111]
There are three images in this example that explain how the NanoVer server structure works, and _all of them say Narupa where they should say NanoVer_. Would someone be able to remake these images to correct for this?

**Comment by Ragzouken** [comment]
I think @jbarnoud said that the source files for these images no longer exist, so we probably need to do them from scratch and keep the source in the repo (or docs repo?) this time. This document is also pretty badly out of date, we don't even have an IMD service any more (interactions happen via state) so it probably needs to be completely revised.

**Comment by hjstroud** [comment]
This issue affects the diagrams in:

- [ ] frame.ipynb
- [ ] servers.ipynb

In terms of the architectural information, these notebooks contain most of the information, but it may be worth checking over `commands_and_state.ipynb` to make sure the State Synchronisation section is correct too.
