### ISSUE TITLE
OpenMMIMDRunner fails to import in visualisations.ipynb

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#113]
When running the second cell of this tutorial, an error is thrown when running `from nanover.ase.openmm import OpenMMIMDRunner`, stating `ImportError: cannot import name 'OpenMMIMDRunner' from 'nanover.ase.openmm'`. Is this because this wrapper is depreciated?

Speaking to @rhoslynroebuck about this, it appears this is a general problem (occurred on both of our machines, Mac and Windows), and she suggested that this line could be replaced with one of the following:
`from nanover.ase.openmm import ASEOpenMMRunner`
`from nanover.openmm import OpenMMRunner`

What do you think @jbarnoud @Ragzouken ? I am happy to fix this in a new PR if either of these solutions are suitable!

**Comment by Ragzouken** [comment]
Yup definitely an oversight of the deprecation: Rho's first suggestion should be the right one, please go ahead
