### ISSUE TITLE
Two tests failing sporadically in python-libraries/nanover-core/tests/test_frame_server.py

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#116]
Two of the tests in python-libraries/nanover-core/tests/test_frame_server.py are failing sporadically (at least they are on Mac). It seems that the tests that fail are consistent (i.e. when failures occur they do so due to at least one of two tests, not a random selection of tests), and that they _do not necessarily both fail during a given run_. In fact, they don't fail every time the tests are performed: sometimes the tests run to completion without failures. Both of the tests fail due to a failed assertion error, detailed below.

`FAILED python-libraries/nanover-core/tests/test_frame_server.py::test_subscribe_frames_frame_interval[0.1-subscribe_frames_async] - assert 0.0050404080687540265 < 0.005
FAILED python-libraries/nanover-core/tests/test_frame_server.py::test_subscribe_frames_frame_interval[0.1-subscribe_last_frames_async] - assert 0.005063856310403805 < 0.005`

I don't think the numbers that fail the tests are the same each time the tests fail, they just take the form 0.005(something small but non-zero).

**Comment by Ragzouken** [comment]
@hjstroud we've just merged changes that introduce additional reliability to an underlying part of the thing tested here, and additional tests for that part. Can you determine if this has improved these sporadic failures for you? (Or otherwise if the failures now also occur in the tests for `yield_interval` in `test_timing.py`?)

**Comment by hjstroud** [comment]
The good news: whatever has changed seems to stop the sporadic failure of the two tests that are the subject of this issue! And it doesn't seem to have introduced failures to either `yield_interval` or `test_timing.py`!

The less good news: there is now a test in `python-libraries/nanover-openmm/tests_nanover_openmm/test_runner.py` that seems to fail consistently when running all of the tests, but doesn't fail when running that test file in isolation. When it fails, it does so with messages like

`FAILED python-libraries/nanover-openmm/tests_nanover_openmm/test_runner.py::TestRunner::test_throttling[1-5] - assert 0.20507699400020232 == 0.2 ± 5.0e-03`

or

`FAILED python-libraries/nanover-openmm/tests_nanover_openmm/test_runner.py::TestRunner::test_throttling[5-30] - assert 0.03849816671364741 == 0.03333333333333333 ± 5.0e-03`

However, is this then the subject of another issue?

**Comment by Ragzouken** [comment]
Yeah less close this as fixed and raise another issue that that test is now failing
