### ISSUE TITLE
The contributors file needs updating

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#119]
The [Contributors file](https://github.com/IRL2/nanover-protocol/blob/main/CONTRIBUTORS.md) needs updating with the correct affiliations.

**Comment by jbarnoud** [comment]
I think that's reasonable. My affiliation changed in 2021.

**Comment by rhoslynroebuck** [comment]
I've opened a PR to close this issue. We spoke about how to format these contributors in meeting the other day and decided to just add a running list of contributors (without a date), with their affiliations correct as of the last time they contributed to the code.
