### ISSUE TITLE
python-libraries/nanover-mdanalysis/src/nanover/mdanalysis/universe.py

### ISSUE THREAD

**Issue by jc14269** [IRL2/nanover-protocol#131]
Getting errors when trying to hide solvent molecules

``` MDAnalysis.coordinates.timestep import Timestep ``` 

gives the error

ModuleNotFoundError: No module named 'MDAnalysis.coordinates.timestep'

Fixed it changing to

```from MDAnalysis.coordinates.base import Timestep ```

**Comment by Ragzouken** [comment]
@jc14269 is this still an issue for you?
