### ISSUE TITLE
Some confusion in unit conversion in MDAnalysis/NanoVer

### ISSUE THREAD

**Issue by Ragzouken** [IRL2/nanover-protocol#146]
In https://github.com/IRL2/nanover-protocol/blob/main/python-libraries/nanover-mdanalysis/src/nanover/mdanalysis/converter.py#L310-L317 there is what is probably a nanometer/angstrom conversion, but it's not documented exactly.

`NanoverReader` also does a unit conversion, and a parameter to skip it (though it's not clear how to use it without unit conversion).

Need to figure out which units are which in which cases and where conversions should and should not happen.

Causing some confusion with dealing with recordings/playback.

**Comment by jbarnoud** [comment]
MDAnalysis uses Angstrom. NanoVer and OpenMM use nanometers.

**Comment by Ragzouken** [comment]
Clarified in https://github.com/IRL2/nanover-protocol/pull/166
