### ISSUE TITLE
LAMMPS tutorial not working

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#184]
The [LAMMPS tutorial](https://github.com/IRL2/nanover-protocol/blob/main/examples/lammps/lammps_client_server.ipynb) is currently not working. 

The issue starts with the line `atoms = frame_data_to_ase(client.first_frame, topology=True, positions=False)`, which raises a NoneType error.

This raises the question of whether we are able to maintain the LAMMPS integration. 

We have been discussing using the `state-utils` repo as a place to put unmaintained utilities scripts/code (see the issue on the repo [here](https://github.com/IRL2/state-utils/issues/6)). We could move these tutorials to that repo so that they are still available for use but people are aware that they are not being maintained. Otherwise, we should either remove this tutorial or update it so that it's working.

**Comment by Ragzouken** [comment]
Agree that it's unclear whether we are able to maintain it. I'm not sure if anyone actually uses it--possibly @jc14269 or @mcsloy ? If we do want to continue supporting it then it'd be ideal to update it to fit in with `OmniRunner` to make it a little less work to maintain.

**Comment by jc14269** [comment]
The problem with LAMMPS data files is that they don't inherently specify atom types but instead atom masses. We've got around when visualising LAMMPS trajectories in VR by using dictionaries to convert the masses to atom elements.

But I haven't used it really at all apart from to visualise a trajectory, so I'm not really sure if its worth it at this point.

**Comment by Ragzouken** [comment]
Closed since we aren't supporting LAMMPS for now
