### ISSUE TITLE
Spurious test failure

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#21]
This test failed, but does not always fail: https://github.com/IRL2/narupa-protocol/actions/runs/6454186086/job/17519370401#step:7:41

**Comment by Ragzouken** [comment]
Log for this no longer exists -- @jbarnoud do you remember which test it was, or if it's covered in another issue?

**Comment by jbarnoud** [comment]
I do not remember. I guess we can just close the issue until the problem pops up again.
