### ISSUE TITLE
Tutorial notebooks using soon-to-be deprecated runners

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#211]
We need to update the jupyter notebook tutorials to move from the omm and ase-omm runners to using the omni runner. 

- [x] basics
- [x] mdanalysis
- [x] openmm
- [ ] fundamentals
- [ ] ase
- [x] lammps [EDIT: not currently planned]

Note that not all of the notebooks use the runners, but they should be checked.

**Comment by Ragzouken** [comment]
all notebooks now use omni
