### ISSUE TITLE
Missing an OmniRunner tutorial notebook

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#213]
At the moment we are looking to switch to using the OmniRunner, which has slightly different functionality to the existing runners, but there currently aren't any Jupyter notebooks that detail how this works. It might be worthwhile adding a notebook that details how to use the OmniRunner, and this would probably be best suited to the `fundamentals` directory.

**Comment by Ragzouken** [comment]
all notebooks now use omni and https://github.com/IRL2/nanover-protocol/issues/256 will cover a more complex case
