### ISSUE TITLE
Running the packaging tests takes too long

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#22]
Running the tests for the conda packages is too slow. It takes around 7 minutes for the linux version of the test, and 13 minutes for the Windows version which delays merge requests. Of this time, installing Narupa is the slowest step. It takes 4 minutes on linux and 6 minutes on Windows.

**Comment by Ragzouken** [comment]
Is this still outstanding? The CI still takes a while but I think it's much faster than described here and it seems dependencies no longer fail to solve?

**Comment by jbarnoud** [comment]
It is less of an issue but the windows tests still take 5 minutes to run.

**Comment by Ragzouken** [comment]
Here are the numbers for a recent run:
![image](https://github.com/IRL2/nanover-protocol/assets/527158/24d13525-94ae-47cf-83d2-669d6c68b792)

I don't see any relevant warnings or errors in the longest running parts. Is there anything we can do to speed this up--tweaking the windows setup somehow? reducing how many dependencies need to be downloaded/installed? I don't really know what's possible.

**Comment by jbarnoud** [comment]
I am afraid it is just everything being a tad slower on Windows. Not sure there is anything we can do.

**Comment by Ragzouken** [comment]
I will close this since there's no further action we can take.
