### ISSUE TITLE
ASEOpenMMSimulation/OmniRunner not working properly

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#230]
It is unclear exactly what the issue is, but there are a number of things that seem to be broken when running the ASE tutorial notebooks using the OmniRunner with an ASEOpenMMSimulation rather that using the old runners. The issues encountered so far include:

- All of the atoms appearing as hydrogens (white balls), regardless of how they are defined in the simulation input
- The topology of the systems don't seem to be being read correctly (when viewed using the NGLView client): the constituent atoms of the "graphene sheet" are not bonded in the graphene example, and in the nanotube example the methane atoms are not bonded but the nanotube appears to have many bonds
- Bonds seem to appear and disappear when the methane enters the nanotube (when using iMD-VR)
- The graphene example runs _really_ slowly, somewhere in the region of two fps

When using the old runners, none of these problems occur.

**Comment by Ragzouken** [comment]
This should be the fix, if you could try it: https://github.com/IRL2/nanover-protocol/pull/232
