### ISSUE TITLE
Cannot attach DCD reporter without loading the simulation first (examples)

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#239]
In the `openmm_polyalanine.ipynb` example notebook, when running only the cells necessary to record a trajectory it is not possible to attach a DCD reporter to the simulation, and you instead get the following error: `AttributeError: 'NoneType' object has no attribute 'reporters'`. 

This can be fixed by loading the simulation _before_ attaching the reporter (i.e. `{sim_name}.load()`). In the short term at least, this notebook should be updated to reflect this. @Ragzouken is this expected behaviour?

**Comment by rhoslynroebuck** [comment]
Closed by #240
