### ISSUE TITLE
ASE simulations that don't use OpenMM don't have a simulation class suitable for the OmniRunner

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#241]
Currently we can run simulations using OpenMM with or without ASE (OpenMMSimulation and ASEOpenMMSimulation, respectively), but we don't have a corresponding ASESimulation class for running simulations using ASE via the OmniRunner. This is relevant for the `basic_example.ipynb` and `openmm_neuraminidase.ipynb` notebooks in the ase examples folder.

**Comment by Ragzouken** [comment]
Looking over it, these are examples that deliberately avoid using the runners, instead using `NanoverASEDynamics`. I think it can be made to work with the Omni runners easily, but I think need to avoid reconstructing the dynamics when resetting.
