### ISSUE TITLE
Deprecation warnings compiling nanover-protocol

### ISSUE THREAD

**Issue by phuddha** [IRL2/nanover-protocol#247]
When compiling Nanover protocol as described in the Readme for Developers there are a bunch of deprecation warnings:

  DEPRECATION: Legacy editable install of nanover-jupyter==0.1.0 from file:///Users/phil/Development/Nanover/nanover-protocol/python-libraries/nanover-jupyter (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457 

DEPRECATION: Legacy editable install of nanover-lammps==0.1.0 from file:///Users/phil/Development/Nanover/nanover-protocol/python-libraries/nanover-lammps (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

  DEPRECATION: Legacy editable install of nanover-mdanalysis==0.1.0 from file:///Users/phil/Development/Nanover/nanover-protocol/python-libraries/nanover-mdanalysis (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

  DEPRECATION: Legacy editable install of nanover-omni==0.1.0 from file:///Users/phil/Development/Nanover/nanover-protocol/python-libraries/nanover-omni (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

 DEPRECATION: Legacy editable install of nanover-openmm==0.1.0 from file:///Users/phil/Development/Nanover/nanover-protocol/python-libraries/nanover-openmm (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457

**Comment by Ragzouken** [comment]
We need to change this before next year: https://github.com/pypa/pip/issues/11457

May need this: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
