### ISSUE TITLE
Dependency issue when installing nanover-server via conda

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#257]
I am getting an issue where I cannot install `nanover-server` in a new conda environment. I follow the usual workflow:

```
conda create -n nanover "python>3.11"
conda activate nanover
conda install -c irl -c conda-forge nanover-server
```

And I get the following error:

![image](https://github.com/user-attachments/assets/5aa1eece-6ec0-48ae-a8c6-6f2721d7ef00)

Note that I am now also getting this warning about Libmamba that I've not seen before: `Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE`. I'm not sure if it's related to the dependency error above, but if not then I'll create a new issue specifically for this.

Note that I tried updating conda but this didn't help.

**Comment by rhoslynroebuck** [comment]
I forgot to add a screenshot of when I created the conda env, which was done immediately before the screenshot above. This is the entire thread:

![image](https://github.com/user-attachments/assets/b6ec7afa-1010-4ca8-af43-adce5e3928a6)

![image](https://github.com/user-attachments/assets/833db49a-76bc-4dbb-8eeb-d8c83b0ffb4d)

**Comment by Ragzouken** [comment]
It seems the openmm package does not support python 3.13, we will need to make that explicit in the installation instructions

**Comment by rhoslynroebuck** [comment]
Closed by this PR in the nanover-docs repo: https://github.com/IRL2/nanover-docs/pull/117
