### ISSUE TITLE
CI fails systematically

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#31]
All jobs in CI fail when executing `conda install`. Is this a transient error due to an external factor or is this an issue with our CI?

In practice, `conda install` seems to succeed, but ends with an exit code of 1 indicating failure.

**Comment by jbarnoud** [comment]
The issue is hidden behind a workaround. We would need to remove the workaround to see if it is fixed.

**Comment by Ragzouken** [comment]
maybe it's this:
![image](https://github.com/IRL2/nanover-protocol/assets/527158/05df47ea-988d-4e49-a536-33d8ac525873)
