### ISSUE TITLE
Increase minimum python version to 3.11

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#60]
This would fix #57 and clarify the minimum version of python we depend on. It used to be that 3.8 was out maximum supported version of python because of openmm and pyosc. Openmm does not have this limitation anymore. Pyosc may still be an issue but the library does not look supported anymore and we only use it in a prototype.

**Comment by jbarnoud** [comment]
> I can try converting the OSC stuff to https://pypi.org/project/python-osc/ if it looks viable?

I'd say it is low priority but it would be nice to do.

**Comment by Ragzouken** [comment]
I realised this is actually the python osc library we are already using... I tried running the tests on python 3.11 and everything (including OSC tests) passed except one of the GRPC utilities, so I think the OSC isn't a problem at least
