### ISSUE TITLE
Build the documentation on github action

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#7]

**Comment by Ragzouken** [comment]
Issue: When you push on NanoVer protocol, it does not trigger the NanoVer repo to rebuild the docs, this is a manual action right now.

**Comment by Ragzouken** [comment]
Related to https://github.com/IRL2/nanover/issues/3

**Comment by hjstroud** [comment]
Closed with #286, thank you @rhoslynroebuck for helping get this going!
