### ISSUE TITLE
Locks unlimited in time have undefined behaviour

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#81]
State locks have all the facilities to handle a lock without timeout (for instance [here](https://github.com/IRL2/nanover-protocol/blob/6b7f45bed2c325c85120b2a5157bc9101e493052/python-libraries/nanover-core/src/nanover/utilities/key_lockable_map.py#L37)). Such a permanent lock would occur if the timeout is set to `None`, see https://github.com/IRL2/nanover-protocol/blob/6b7f45bed2c325c85120b2a5157bc9101e493052/python-libraries/nanover-core/src/nanover/state/state_service.py#L217. However, the protocol does not allow the timeout to be `None` as a `None` timeout in the lock update request would remove the lock (See [the protocol definition](https://github.com/IRL2/nanover-protocol/blob/6b7f45bed2c325c85120b2a5157bc9101e493052/protocol/nanover/protocol/state/state_service.proto#L44-L47) and its [implementation](https://github.com/IRL2/nanover-protocol/blob/6b7f45bed2c325c85120b2a5157bc9101e493052/python-libraries/nanover-core/src/nanover/state/state_service.py#L178-L182)).

Do we want to keep this behaviour in the code or match the protocol more closely? Keeping the code as is *may* allow a server to create unlimited locks, which may be desirable, but it could lead to unreachable code and cause devs to misinterpret the expected behaviour, which is bad.

**Comment by jbarnoud** [comment]
Note that the rust server has the same behaviour as the python one: both would allow unlimited locks but it is unreachable in both servers.

**Comment by jbarnoud** [comment]
Pinging @Ragzouken for an opinion.

**Comment by Ragzouken** [comment]
First instinct is that unlimited locks are a feature of `KeyLockableMap` that we simply don't use/expose for state service. 

As far as I can tell there aren't actually any tests for lock expiration for either `KeyLockableMap` or state service. I think expiry was added later to deal with the issue of clients exiting while moving the box.

The code for non-expiring locks is trivial to remove and later restore, so it wouldn't hurt to remove it if that seems sensible. Maybe in the future we would like to support client's creating non-expiring locks when we have the lifecycle stuff to expire them on client exit. Maybe locks is something that gets a full review when state lifecycle stuff comes around anyway.

No strong opinion.

**Comment by jbarnoud** [comment]
> First instinct is that unlimited locks are a feature of KeyLockableMap that we simply don't use/expose for state service.

I am happy to close the issue from this answer. I let you choose to close it or not, in case you'd like to keep it open for when you look at the life cycle.
