### ISSUE TITLE
FrameData is limited in size

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#84]
A simulation frame is represented by a `FrameData` that is sent as a single gRPC message. Because a gRPC message is limited by default to 4MB, a frame is limited to what can be represented in that volume. This limits the size of the system we can simulate and stream.

The maximum system size is related to the number of particles in the system but not linearly so. Indeed, the limit accounts for the topology that depends on the number of residues and chains and the number of bonds. For the same number of particles, a system with explicit water is likely to take more space than a system with a single-chain protein, except if all the water molecules are counted as a single residue. The size limit also needs to account for optional data that can be included such as forces, velocities, energies, user forces...

There are short-term solutions to the issue that would push the size limit:
* increase the size of a gRPC message
* enable HTTP compression

These solutions would push the size limit but not remove it. An actual solution would be to stream chunks of frames rather than streaming frames. This adds some complexity but would allow infinitely sized frames. At this point, the issue will become the time needed to produce and send the frames rather than the size of the frame itself.

Any of these changes would be breaking and would require changes on both the servers and the clients. The short-term solutions require limited changes as they are configuration values when creating the gRPC connection. The long-term solution is more involved. It could be implemented while keeping the current way of sending frames alongside the new one until the transition is done. Indeed, only larger systems will require the more complex system.

**Comment by Ragzouken** [comment]
For now we will use the built-in unlimited message length and see if there's an issue.
