### ISSUE TITLE
nglview not working with in Jupyter notebook via jupyterlab

### ISSUE THREAD

**Issue by hjstroud** [IRL2/nanover-protocol#88]
When attempting the tutorial in `basic_example.ipynb`, the notebook in `nanover_nglview.ipynb` fails to show the system being simulated, and instead the only output of the `client.view` cell is `NGLWidget()`. This issue does not occur if one uses Jupyter notebook without Jupyterlab, i.e. `conda install jupyter` rather than `conda install jupyterlab`. This may be an issue unrelated to NanoVer itself (a problem with nglview and Jupyterlab), but it may be worth specifying in the documentation that the user should access this view using Jupyter notebook _without_ Jupyterlab.

**Comment by hjstroud** [comment]
Ah I see. Is this something we want to add to the documentation, and close this issue (if it is not actually a problem in practice with the addition to the documentation)?

**Comment by jbarnoud** [comment]
I do not know if it works, but if it does why not adding it to the doc.

**Comment by hjstroud** [comment]
I'll give it a go and see if it works... will report back when I'm done!

**Comment by hjstroud** [comment]
It works! Indeed, I didn't even need to explicitly install ipywidgets---if you install jupyterlab first, when you install nglview jupyterlab_widgets and ipywidgets are automatically installed. However, I can see that if someone has JupyterLab installed in their base environment, it may be necessary to install ipywidgets in the NanoVer conda environment explicitly, and perhaps follow the instructions in the link you sent above. 

I could update the docs to specify that jupyterlab should be installed in the conda environment _before_ nglview, and reference the link for people who already have jupyterlab installed in their base conda env?
