### ISSUE TITLE
Switch to a maintained gRPC library for C#

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#9]
In the C# library, we depend on the gRPC for C# library that [is deprecated](https://grpc.io/blog/grpc-csharp-future/) and [does not officially support Unity](https://github.com/grpc/grpc/issues/22485#issuecomment-1116206421). In practice,  we cannot build Narupa for Unity on arm64, which we need for Meta Quest support.

The recommended library, nowadays, is [gRPC for dotnet](https://github.com/grpc/grpc-dotnet). Therefore, we need to translate our C# codebase to that library.

**Comment by Ragzouken** [comment]
Closed by https://github.com/IRL2/nanover-protocol/pull/47
