### ISSUE TITLE
XML format needs some/more documentation?

### ISSUE THREAD

**Issue by Ragzouken** [IRL2/nanover-protocol#90]
At least I was under the misunderstanding that the XML was standard OpenMM, but rather it's a wrapper of three input files OpenMM would use. Perhaps we should have easy support for providing the files separately.

**Comment by jbarnoud** [comment]
Does that document your concerns: <https://narupa.readthedocs.io/en/latest/python/narupa.openmm.serializer.html>?

Note that this is a link to the old documentation. There is an issue with the new one (<https://narupa.readthedocs.io/en/latest/python/narupa.openmm.serializer.html>) but the content is the same.

**Comment by Ragzouken** [comment]
Ah okay. Probably my real concern then is how easily you can find the path to go from your own OpenMM files to running NanoVer CLI. Maybe we should have something in the readme either saying outright or pointing to the information that `nanover-omm-ase` takes an XML in a particular format and that it can be constructed easily in a certain way--the single OpenMM notebook seems to cover this, we could link it in the list of tutorials maybe?

**Comment by jbarnoud** [comment]
One could also point to https://github.com/IRL2/nanover-protocol/blob/main/examples/openmm/OpenMM%20runner.ipynb that goes through the process of building a simulation with OpenMM and generating the XML file from it.

Some time ago, I also wrote a tutorial for collaborators in Leeds.
[protein_tutorial.zip](https://github.com/IRL2/nanover-protocol/files/15221614/protein_tutorial.zip)

**Comment by Ragzouken** [comment]
@hjstroud @rhoslynroebuck since you two seem to be on top of the docs lately, maybe you could either close this if everything is fine already or propose a concrete change?

**Comment by rhoslynroebuck** [comment]
I have added some information about running an OpenMM server through the command line + linked to the jupyter notebook for serialising an OpenMM system. This depends on this issue being fixed in the Nanover repo: https://github.com/IRL2/nanover/issues/10

**Comment by jbarnoud** [comment]
https://github.com/IRL2/nanover/issues/10 is fixed now.

**Comment by hjstroud** [comment]
> [https://narupa.readthedocs.io/en/latest/python/narupa.openmm.serializer.htm](https://narupa.readthedocs.io/en/latest/python/narupa.openmm.serializer.html)

I think for me making the description of the XML style we use in NanoVer as accessible as possible is really important. It looks like this page does address the concerns I had, so definitely making sure this information is in the NanoVer documentation would be good, and also maybe highlighting it somewhere in the documentation about the tutorials (Possibly in the OpenMM specific tutorials?) would be helpful to make it abundantly clear what the file actually is and how it may differ to the XML file formats used in a raw OpenMM simulation.

**Comment by hjstroud** [comment]
Actions:

- [ ] Add the information from the docstrings about XML format to the `OpenMM Runner` notebook
- [ ] Rename notebook appropriately e.g. `Setup and run OpenMM simulations`

**Comment by Mohamed-Dhouioui** [comment]
Closing this because it has been resolved in this [PR](https://github.com/IRL2/nanover-docs/pull/115)
