### ISSUE TITLE
Switch simulation

### ISSUE THREAD

**Issue by jbarnoud** [IRL2/nanover-protocol#91]
To be in parity with the rust server, the python server should be able to change simulation. It needs to implement the `playback/list`, `playback/load`, and `playback/next` commands. It should also implement the `system.simulation.counter` key in the `FrameData`.

**Comment by Ragzouken** [comment]
Do you remember if there was a reason we put off support for this? Was there some architectural difficulty we need to discuss?

**Comment by jbarnoud** [comment]
I do not recall we pit off support for this. I implemented it for the rust server and did not take the time to do it for the python server as well, that's it.

**Comment by Ragzouken** [comment]
Oh okay, I thought that we had intended to do it back in Bristol and had some issue, but it was many years ago so I'm probably thinking of something else.

**Comment by jbarnoud** [comment]
Indeed, it was in the TODO list forever. I think we just never needed it urgently enough.

**Comment by Ragzouken** [comment]
closed by https://github.com/IRL2/nanover-protocol/pull/135
