### ISSUE TITLE
Move installation info about packages for tutorials before the list of tutorials in README

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#95]
In the README, the list of tutorials comes before the information about the required packages and how to install them. This would be better switched around.

**Comment by rhoslynroebuck** [comment]
Alternatively, we could add a note to say that installation instructions are below. @hjstroud said that he tried to run the tutorials before reading the installation instructions below. 

What are your thoughts @hjstroud ?

**Comment by jbarnoud** [comment]
Either a note or a table of contents.
